"""add_focus_settings_and_focus_session_tables

Revision ID: d050b39a4b74
Revises: a2174b22dbf4
Create Date: 2026-08-16 20:59:19.177342

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d050b39a4b74"
down_revision: str | Sequence[str] | None = "a2174b22dbf4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "focus_sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "session_type",
            sa.Enum(
                "FOCUS",
                "BREAK",
                "LONG_BREAK",
                name="sessiontype",
                native_enum=False,
                length=20,
            ),
            server_default=sa.text("'focus'"),
            nullable=False,
        ),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("planned_duration", sa.Integer(), nullable=False),
        sa.Column("actual_duration", sa.Integer(), nullable=True),
        sa.Column(
            "completed", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_focus_sessions_user_id_started_at",
        "focus_sessions",
        ["user_id", "started_at"],
        unique=False,
    )
    op.create_table(
        "pomodoro_settings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "focus_duration", sa.Integer(), server_default=sa.text("25"), nullable=False
        ),
        sa.Column(
            "short_break_duration",
            sa.Integer(),
            server_default=sa.text("5"),
            nullable=False,
        ),
        sa.Column(
            "long_break_duration",
            sa.Integer(),
            server_default=sa.text("15"),
            nullable=False,
        ),
        sa.Column(
            "sessions_before_long_break",
            sa.Integer(),
            server_default=sa.text("4"),
            nullable=False,
        ),
        sa.Column(
            "auto_start_focus",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "auto_start_break",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pomodoro_settings")
    op.drop_index("ix_focus_sessions_user_id_started_at", table_name="focus_sessions")
    op.drop_table("focus_sessions")
    # ### end Alembic commands ###
