"""update_time_defaults_to_seconds

Revision ID: 5025146908d9
Revises: d050b39a4b74
Create Date: 2026-08-24 00:23:33.324555

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5025146908d9"
down_revision: str | Sequence[str] | None = "d050b39a4b74"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "pomodoro_settings",
        "focus_duration",
        existing_type=sa.INTEGER(),
        server_default=sa.text("1500"),
        existing_nullable=False,
    )
    op.alter_column(
        "pomodoro_settings",
        "short_break_duration",
        existing_type=sa.INTEGER(),
        server_default=sa.text("300"),
        existing_nullable=False,
    )
    op.alter_column(
        "pomodoro_settings",
        "long_break_duration",
        existing_type=sa.INTEGER(),
        server_default=sa.text("900"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "pomodoro_settings",
        "long_break_duration",
        existing_type=sa.INTEGER(),
        server_default=sa.text("15"),
        existing_nullable=False,
    )
    op.alter_column(
        "pomodoro_settings",
        "short_break_duration",
        existing_type=sa.INTEGER(),
        server_default=sa.text("5"),
        existing_nullable=False,
    )
    op.alter_column(
        "pomodoro_settings",
        "focus_duration",
        existing_type=sa.INTEGER(),
        server_default=sa.text("25"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
